import React, { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Tooltip from './Tooltip'
import { proficiencyLabel } from '../utils/goalRisk'
import './WorkforceCharts.css'
const riskColor = count => count <= 2 ? 'var(--critical)' : count <= 4 ? 'var(--warning)' : 'var(--primary)'
export default function SkillHolderNetwork({ skillsWithRisk, employees }) {
  const [selected, setSelected] = useState(null), [tip, setTip] = useState(null)
  const nodes = useMemo(() => {
    const ordered = [...skillsWithRisk].sort((a, b) => a.holderCount - b.holderCount || a.skill.name.localeCompare(b.skill.name))
    return ordered.map((item, i) => { const angle = i * Math.PI * 2 / Math.max(1, ordered.length) - Math.PI / 2; const radius = i % 2 ? 170 : 110; return { ...item, x: 360 + Math.cos(angle) * radius, y: 340 + Math.sin(angle) * radius, r: 7 + 15 / Math.sqrt(Math.max(1, item.holderCount)) } })
  }, [skillsWithRisk])
  const people = useMemo(() => employees.map((employee, i) => { const angle = i * Math.PI * 2 / Math.max(1, employees.length) - Math.PI / 2; return { ...employee, x: 360 + Math.cos(angle) * 300, y: 340 + Math.sin(angle) * 300 } }), [employees])
  const positions = new Map(people.map(person => [person.id, person]))
  const focused = selected?.type === 'skill' ? nodes.find(node => node.skill.id === selected.id) : people.find(person => person.id === selected?.id)
  const activeSkills = selected?.type === 'employee' ? nodes.filter(node => node.holders.some(holder => holder.id === selected.id)) : focused && selected?.type === 'skill' ? [focused] : []
  const activePeople = new Set(activeSkills.flatMap(node => node.holders.map(holder => holder.id)))
  const showTip = (event, label) => { const box = event.currentTarget.getBoundingClientRect(); setTip({ x: Math.min(box.left, window.innerWidth - 300), y: Math.min(box.top, window.innerHeight - 110), label }) }
  return <>
    <div className="network-controls"><label>Focus a capability<select value={selected?.type === 'skill' ? selected.id : ''} onChange={event => setSelected(event.target.value ? { type: 'skill', id: event.target.value } : null)}><option value="">All capabilities</option>{nodes.map(node => <option value={node.skill.id} key={node.skill.id}>{node.skill.name} · {node.holderCount} holders</option>)}</select></label><button onClick={() => setSelected(null)}>Reset view</button></div>
    <div className="network-key"><span><i style={{background:'var(--critical)'}}/>Critical · 0–2 holders</span><span><i style={{background:'var(--warning)'}}/>Watch · 3–4</span><span><i style={{background:'var(--primary)'}}/>Distributed · 5+</span><span>Larger skill nodes = rarer skills · Outer dots = employees</span></div>
    <div className="network-layout"><div className="network-chart"><svg viewBox="0 0 720 680" role="group" aria-label="Interactive skill and employee network. Select a capability or employee to inspect its real connections.">
      <circle cx="360" cy="340" r="300" fill="none" stroke="var(--hairline)" strokeDasharray="3 6"/>
      {nodes.flatMap(node => node.holders.map(holder => { const person = positions.get(holder.id); if (!person) return null; const highlighted = selected && (selected.type === 'skill' ? selected.id === node.skill.id : selected.id === holder.id); return <line key={`${node.skill.id}-${holder.id}`} x1={node.x} y1={node.y} x2={person.x} y2={person.y} stroke={riskColor(node.holderCount)} strokeWidth={highlighted ? 1.7 : .6} opacity={selected ? highlighted ? .7 : .025 : .13}/> }))}
      {nodes.map(node => <circle className="network-node" key={node.skill.id} cx={node.x} cy={node.y} r={node.r} fill={riskColor(node.holderCount)} opacity={!selected || activeSkills.includes(node) ? 1 : .2} stroke={selected?.id === node.skill.id ? 'var(--text)' : 'var(--bg)'} strokeWidth="2" tabIndex="0" role="button" aria-label={`${node.skill.name}, ${node.holderCount} holders`} onClick={() => setSelected({ type: 'skill', id: node.skill.id })} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelected({ type: 'skill', id: node.skill.id }) } }} onMouseEnter={event => showTip(event, `${node.skill.name} · ${node.holderCount} holders`)} onMouseLeave={() => setTip(null)} onFocus={event => showTip(event, node.skill.name)} onBlur={() => setTip(null)}/>)}
      {people.map(person => <circle className="network-node" key={person.id} cx={person.x} cy={person.y} r={selected?.id === person.id ? 7 : 4} fill={activePeople.has(person.id) ? 'var(--text)' : 'var(--muted)'} opacity={!selected || activePeople.has(person.id) ? 1 : .2} tabIndex="0" role="button" aria-label={`${person.name}, ${person.role}`} onClick={() => setSelected({ type: 'employee', id: person.id })} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelected({ type: 'employee', id: person.id }) } }} onMouseEnter={event => showTip(event, `${person.name} · ${person.role}`)} onMouseLeave={() => setTip(null)} onFocus={event => showTip(event, person.name)} onBlur={() => setTip(null)}/>)}
    </svg>{tip && <Tooltip x={tip.x} y={tip.y}>{tip.label}</Tooltip>}</div>
    <section className="readiness-panel network-detail"><h2>{focused ? selected.type === 'skill' ? focused.skill.name : focused.name : 'Explore the network'}</h2>{!focused ? <p>Select an inner skill node to see every holder, or an outer employee node to see their capabilities. Connections come from recorded workforce skills, including Beginner proficiency.</p> : selected.type === 'skill' ? <><p className="readiness-data">{focused.holderCount} RECORDED HOLDERS</p>{!focused.holders.length && <p>No internal holders recorded.</p>}<ul>{focused.holders.map(holder => <li key={holder.id}><Link to={`/employees/${holder.id}`}>{holder.name}</Link><small>{holder.role} · {proficiencyLabel(holder.proficiency)}</small></li>)}</ul></> : <><Link to={`/employees/${focused.id}`}>Open employee profile ↗</Link><ul>{activeSkills.map(node => <li key={node.skill.id}>{node.skill.name}<small>{proficiencyLabel(node.holders.find(holder => holder.id === focused.id)?.proficiency)}</small></li>)}</ul>{!activeSkills.length && <p>No skills recorded for this employee.</p>}</>}</section></div>
  </>
}
